### ISSUE TITLE
Enable swagger spec version 3 support

### ISSUE THREAD

**Issue by SergeyMi37** [lscalese/OpenAPI-Client-Gen#30]

**Comment by lscalese** [comment]
Hi @SergeyMi37 ,

I definitely have to do this.
When I have the time, I will work on this enhancement.

I think including a converter in order to convert swagger 2.0 to swagger 3 and write a generator that supports only v 3.

It seems a python library exists for this conversion.  It could be an opportunity to use the benefits of Python support with IRIS.

**Comment by lscalese** [comment]
The development is done.  
The version 2 of this package is not yet available on OpenExchange, because I would like to make some tests before.

**Comment by lscalese** [comment]
Done.

**Comment by SergeyMi37** [comment]
This is great, thanks

**Comment by lscalese** [comment]
Hi @SergeyMi37,
This a complete refactoring, I'm sure we'll find bugs ...
Don't hesitate to send me OpenAPI specification in order to test and reproduce a problem if needed :-)
